#!/usr/bin/env bash
#
# Idempotent development bootstrap for Cursor Cloud Agents.
#
# Runs after the repository is checked out:
#   1. installs Node dependencies (postinstall runs `prisma generate`)
#   2. creates a git-ignored .env.local with dev-safe defaults if absent
#   3. applies Prisma migrations to the local SQLite database
#   4. seeds a MASTER admin so the app can be logged into immediately
#
# The helper scripts and the app resolve a relative `file:` DATABASE_URL
# differently on Linux (they were authored on Windows), so we pin an
# absolute path here to keep the app, Prisma CLI, and scripts consistent.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"
DB_URL="file:${ROOT}/prisma/production.db"

echo "==> Installing dependencies"
npm ci

if [ ! -f .env.local ]; then
  echo "==> Creating .env.local with development defaults"
  cat > .env.local <<EOF
# Local development environment (git-ignored). Generated by setup-cloud-agent.sh.
DATABASE_URL="${DB_URL}"
JWT_SECRET="dev-secret-change-me"
MASTER_ADMIN_EMAIL="admin@example.com"
EOF
else
  echo "==> .env.local already exists, leaving it untouched"
fi

echo "==> Applying database migrations"
export DATABASE_URL="${DB_URL}"
npx prisma migrate deploy

echo "==> Ensuring a development MASTER admin exists (admin@example.com / Admin12345)"
node scripts/create-admin.js admin@example.com Admin12345 "Dev Admin" || true

echo "==> Setup complete"
